// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3b2QrQEjrzpob-K3wIG2roKg7NEm9YgY',
    appId: '1:754984498040:web:4fcb35e1e25ff489930e8d',
    messagingSenderId: '754984498040',
    projectId: 'fir-01-b7618',
    authDomain: 'fir-01-b7618.firebaseapp.com',
    storageBucket: 'fir-01-b7618.firebasestorage.app',
    measurementId: 'G-XX7WVT8MRZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4WKfESLLs9361qtACIHRvGhfwNdZatg',
    appId: '1:754984498040:android:f2f41f2809673159930e8d',
    messagingSenderId: '754984498040',
    projectId: 'fir-01-b7618',
    storageBucket: 'fir-01-b7618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9pPv5ZtFqH-aAEsWHJjEhKX88Juhy60g',
    appId: '1:754984498040:ios:c5a0e8bbe998022c930e8d',
    messagingSenderId: '754984498040',
    projectId: 'fir-01-b7618',
    storageBucket: 'fir-01-b7618.firebasestorage.app',
    iosBundleId: 'com.example.firebaseStart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9pPv5ZtFqH-aAEsWHJjEhKX88Juhy60g',
    appId: '1:754984498040:ios:c5a0e8bbe998022c930e8d',
    messagingSenderId: '754984498040',
    projectId: 'fir-01-b7618',
    storageBucket: 'fir-01-b7618.firebasestorage.app',
    iosBundleId: 'com.example.firebaseStart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3b2QrQEjrzpob-K3wIG2roKg7NEm9YgY',
    appId: '1:754984498040:web:9861c847a8f5ace0930e8d',
    messagingSenderId: '754984498040',
    projectId: 'fir-01-b7618',
    authDomain: 'fir-01-b7618.firebaseapp.com',
    storageBucket: 'fir-01-b7618.firebasestorage.app',
    measurementId: 'G-V9EEKVTYTK',
  );
}
